### ISSUE TITLE
Your wishes for asio-grpc

### ISSUE THREAD

**Issue by Tradias** [WolleTD/asio-grpc-callback#1]
Hi,

cool effort. As I am constantly looking for ways to improve [asio-grpc](https://github.com/Tradias/asio-grpc), I am wondering why you started this "library". Is there any feature or API that you are missing in asio-grpc?

**Comment by WolleTD** [comment]
Hi, cool to read from you.

To be honest, I have not taken too much time looking into asio-grpc. I was checking out gRPC for work and somehow ended up building this over one or two weekends – and now it's in our projects (which I expected, to be fair).
It was also an exercise in C++20 coroutines for me, which I hadn't much chance to work with either until now.

So, that's probably where I'm coming from: We have some experience with C++17 asio in the team, but virtually no experience with C++20 or gRPC. I think the gRPC-API is pretty unwieldy and verbose with all it's contexts, stubs and, well, completion queues, so I tried to build a much more asio-like API that's easy to use by my developers and me.

I guess it's more about the CompletionQueue-API of gRPC than about asio-grpc, so, ehm... Callback-API support?
My "Hello World" Server-Coro is two lines, excluding the timer:
```cpp
auto greet_coro(const Request *request, Reply *reply) -> awaitable<grpc::Status> {
    auto msg = format("Hello {}!", request->name());
    reply->set_greeting(msg);
    co_return grpc::Status::OK;
}
```

Most of that isn't really _my_ effort, though, but the Callback-API, which makes invoking the coroutine three lines as well:
```cpp
ServerUnaryReactor *greet(CallbackServerContext *, const Request *request, Reply *reply) override {   
    auto *reactor = new asio_server_unary_reactor(ex);
    co_spawn(ex, greet_coro(request, reply), default_reactor_handler(reactor));
    return reactor;
}
```

Granted, there are two custom types in this one, but my argument is: I don't have to "request a request" from gRPC in a coroutine per method.

I was able to hide most of the context and reactor management from the library user for both unary and stream calls. Outside of the `co_spawn` wrapping, you should only ever touch `grpc::Status` and your request/reply types.

Compare that to the asio-grpc server coro:
```cpp
{
    grpc::ServerContext server_context;
    helloworld::HelloRequest request;
    grpc::ServerAsyncResponseWriter<helloworld::HelloReply> writer{&server_context};
    co_await agrpc::request(&helloworld::Greeter::AsyncService::RequestSayHello, service, server_context,
                            request, writer, asio::use_awaitable);
    helloworld::HelloReply response;
    response.set_message("Hello " + request.name());
    co_await agrpc::finish(writer, response, grpc::Status::OK, asio::use_awaitable);
}
```

Half of these lines I don't care about, they are gRPC boilerplate. It's already 10x less verbose and more useable than the original completion queue API, but it's still obvious that it grew from there.

I don't see an easy way to hide all these lines without reactor facilities provided by the (relatively new) callback API, though. They are just a product of their time.
I learned gRPC this year and for me it was the obvious way to do it like this, I think the Callback API matches really well with asio (even without C++20).

So, yeah, that's probably it. I'm happy to talk more about this or contribute to asio-grpc. :wink:

**Comment by Tradias** [comment]
Thanks for the write-up.

My hope with asio-grpc was initially to process RPCs on an `asio::io_context` exclusively to avoid the overhead of thread-switching and seamless interop with asio's facilities like timers and sockets. Turns out that is not possible with the CompletionQueue API. So over time, I figured that wrapping the CompletionQueue into an execution_context does at least make the thread switching explicit and that's how asio-grpc was first released to the public. Another goal was to provide only a thin, zero-overhead layer over gRPC's own API of Services and Stubs to avoid delving into API design. After all, the Service/Stub API seems to "working" for people, only the `void* tag` part is annoying which can nicely be replaced with the CompletionToken concept of asio.

Over time, it became clear that people enjoy a more high-level API and so I created the [agrpc::RPC](https://tradias.github.io/asio-grpc/classagrpc_1_1_r_p_c.html) API. It makes client-side RPCs reasonably more concise and harder to misuse in my opinion. A server-streaming RPC could then be implemented like this:

```c++
asio::awaitable<void> server_streaming(agrpc::GrpcContext& grpc_context, example::v1::Example::Stub& stub)
{
    using RPC = agrpc::RPC<&example::v1::Example::Stub::PrepareAsyncServerStreaming>;
    
    grpc::ClientContext client_context; // set deadline, compression, tracing, ...

    example::v1::Request request; 
    // fill request

    RPC rpc = co_await RPC::request(grpc_context, stub, client_context, request);

    example::v1::Response response;
    while (co_await rpc.read(response))
    {
        // process response(s)
    }

    if (!rpc.ok())
    {
        // process error: rpc.status()
    }
}
```

I am now [gathering ideas](https://github.com/Tradias/asio-grpc/issues/45) for something similar on the server-side. The helloworld example that you quoted from asio-grpc is probably not how most people would write their server since it only handles exactly one request. Maybe I should adjust it 😁, because it would look more like this:

```c++
auto request_handler = [&](grpc::ServerContext&, helloworld::HelloRequest& request,
                           grpc::ServerAsyncResponseWriter<helloworld::HelloReply>& writer) -> asio::awaitable<void>
{
    helloworld::HelloReply response;
    response.set_message("Hello " + request.name());
    co_await agrpc::finish(writer, response, grpc::Status::OK);
};
agrpc::repeatedly_request(&helloworld::Greeter::AsyncService::RequestSayHello, service,
                            asio::bind_executor(grpc_context, request_handler));
```

I think here the `request_handler` has a similar focus on Response and Status like in your code. It might be worth looking into creating a custom `grpc_cpp_plugin`-like plugin for protoc. Although I kind of like the fact that asio-grpc works with the vanilla version, people already seem to struggle to install/consume asio-grpc and adding such a plugin would make things even harder.

**Comment by WolleTD** [comment]
Well, to avoid thread switching, we'd have to completely replace the netcode of gRPC with asio sockets, wouldn't we?

The wrapping of the completion queue in an `execution_context` is a major point. I don't even have a way of explicitly spawning work into gRPC, which [is an issue](https://github.com/WolleTD/asio-grpc-callback/blob/main/src/asio-grpc-client.h#L167) in Streams, where I have to use a future and potentially block a gRPC thread to avoid some ugly race.

That also means that all RPC work involves thread switching, because I can't spawn a coroutine in gRPC. Of course, the callbacks _are_ executed in a gRPC thread, but without having an appropriate executor, the only way of doing work there is by not being executor-correct.

Consider this code from `hello-world-client.h`:
```cpp
class HelloClient {
public:
    explicit HelloClient(asio::io_context &ctx, const std::shared_ptr<Channel> &channel)
        : ctx_(ctx), stub_(Hello::NewStub(channel)) {}

    template<typename CompletionToken>
    auto greet(const Request &request, CompletionToken &&token) {
        return async_initiate_grpc<Reply>(
                ctx_, token, [this, &request](grpc::ClientContext *ctx, Reply *reply, auto &&handler) {
                    stub_->async()->greet(ctx, &request, reply, std::forward<decltype(handler)>(handler));
                });
    }

    using GreetStream = StreamChannel<StreamReply>;

    GreetStream greet_stream(const StreamRequest &request) {
        return {ctx_,
                [this, &request](auto *ctx, auto *reactor) { stub_->async()->greet_stream(ctx, &request, reactor); }};
    }

private:
    asio::io_context &ctx_;
    std::unique_ptr<Hello::Stub> stub_;
};
```

This is user-code that would be manually written for every service, but it has an interface comparable to asio io-objects. `async_initiate_grpc` does everything required for executor-correctness and maps cancellation slots through gRPC. I assume your `RPC::request` does similar things.
I don't provide access to ClientContext, but that would be possible to change or even provide wrapping functions for. While you resolve the function to call via template parameters, I just let the user write a lambda.

Finally, the `async()->greet()` line is the Callback-API: it just takes a Callable (must be copyable, apparently) that is called from within gRPC when the request completes. `async_initiate_grpc` provides a `handler` there hiding all the boilerplate required.

The stream is another story, but kind of the same. Because I don't have access to the CompletionQueue, I instead built my stream object with `asio::experimental::concurrent_channel`. I can't get my head around how that would have worked out with a CQ executor right now.

I think, besides my wrapping in a `HelloClient` object and the different executors, the similarities are in `RPC::response` and `async_initiate_grpc/StreamChannel`. I opted to completely separate the two concepts, but I think it would be possible to write a `HelloClient` with nearly the same interface in terms of `agrpc::RPC`.
But then again, I can also get away with 250 lines and the callback API, so – why? Well, probably because of the CQ executor, but I'd like _only_ that and just `bind_executor` my way or something? :wink:

---

Thanks for your updated example, I've seen similar things in other files but wasn't sure. The async hello world example in gRPC itself is worse, though :smile:
Still, the CompletionQueue leaks through asio-grpc: we "request" the request. I know where it comes from, but I just dislike that pattern, the callback API hides it from us.

Besides that, and maybe to the point of a better server API for asio-grpc:
Instead of `agrpc::finish`, I provide a `default_reactor_handler` that can be given to a `co_spawn` (or called like a regular completion handler from C++17 callbacks) and thus enable using `co_return status;` and throwing exceptions. Part of that is the `ServerUnaryReactor` provided by gRPC that hides any `writer`, though.

It's amazing how similar the results are. Basically, `agrpc::repeatedly_request` does in one step what the Callback-API and my `co_spawn/default_reactor_handler` do in two. But again: with only 250 lines of my own.

---

Here's what I'm thinking: the Callback API of gRPC is really good. asio-grpc does a lot of things the Callback API does, too. Consider adapting asio-grpc to the Callback API and gRPC-provided reactor framework. Keep the gRPC execution context, because that's really cool. The whole thing requires that we can combine Callback-API and a CompletionQueue, but I think we can.
I really like the execution part, but I favor the three-liner Callback-`greet` over the "request" pattern. And I guess future developers learning gRPC from scratch (e.g. not from existing codebases that use the old APIs) will increasingly, too.

**Comment by Tradias** [comment]
> Well, to avoid thread switching, we'd have to completely replace the netcode of gRPC with asio sockets, wouldn't we?

GRPC is working on something they call [EventEngine](https://github.com/grpc/grpc/tree/master/include/grpc/event_engine) which should make it possible to inject asio sockets into some parts of gRPC's netcode.

------

I am not so worried about the code size. Sure 250 lines own sounds nice, but asio-grpc has many more features, like support for std::execution, and provides much better performance that I am willing to write more code myself. After all, that is what libraries are good at - hide all that pluming code.

I actually favor the `finish` over the `co_return status;` style, as it allows users to run some cleanup code after the RPC is done. And upon exception I can easily call something like `ServerContext::TryCancel` in the destructor of `agrpc::RPC`.

I have started to peel away at the possible customizations that a `register_request_handler` function would need in asio-grpc, trying to see which ones can be combined and how. There is `notify_when_done` - on or off, `protobuf::Arena` - one per request or one for multiple requests, any dynamic memory allocations (support for asio::awaitable is essentially part of this), a type that users can name in their request_handler if they want to hide its implementation in a cpp file, maybe a hook to insert tracing and metrics and probably some more I haven't thought of yet: https://github.com/Tradias/asio-grpc/blob/high-level-server/test/src/test_high_level_server_20.cpp#L182-L203
